boot.o: boot.S multiboot.h x86_desc.h types.h
flush_tlb.o: flush_tlb.S
intr_link.o: intr_link.S
system_call_linkage.o: system_call_linkage.S x86_desc.h types.h
x86_desc.o: x86_desc.S x86_desc.h types.h
fs_system.o: fs_system.c fs_system.h lib.h types.h keyboard.h multiboot.h \
  x86_desc.h i8259.h debug.h tests.h systemcalls.h terminal.h \
  scheduling.h paging.h rtc.h idt.h intr_link.h
i8259.o: i8259.c i8259.h types.h lib.h keyboard.h multiboot.h x86_desc.h \
  debug.h tests.h systemcalls.h terminal.h scheduling.h fs_system.h \
  paging.h rtc.h idt.h intr_link.h
idt.o: idt.c idt.h multiboot.h types.h x86_desc.h lib.h keyboard.h \
  i8259.h debug.h tests.h systemcalls.h terminal.h scheduling.h \
  fs_system.h paging.h rtc.h intr_link.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h keyboard.h \
  i8259.h debug.h tests.h systemcalls.h terminal.h scheduling.h \
  fs_system.h paging.h rtc.h idt.h intr_link.h
keyboard.o: keyboard.c keyboard.h multiboot.h types.h x86_desc.h lib.h \
  i8259.h debug.h tests.h systemcalls.h terminal.h scheduling.h \
  fs_system.h paging.h rtc.h idt.h intr_link.h
lib.o: lib.c lib.h types.h keyboard.h multiboot.h x86_desc.h i8259.h \
  debug.h tests.h systemcalls.h terminal.h scheduling.h fs_system.h \
  paging.h rtc.h idt.h intr_link.h
paging.o: paging.c paging.h types.h x86_desc.h lib.h keyboard.h \
  multiboot.h i8259.h debug.h tests.h systemcalls.h terminal.h \
  scheduling.h fs_system.h rtc.h idt.h intr_link.h
rtc.o: rtc.c rtc.h multiboot.h types.h x86_desc.h lib.h keyboard.h \
  i8259.h debug.h tests.h systemcalls.h terminal.h scheduling.h \
  fs_system.h paging.h idt.h intr_link.h
scheduling.o: scheduling.c scheduling.h types.h lib.h keyboard.h \
  multiboot.h x86_desc.h i8259.h debug.h tests.h systemcalls.h terminal.h \
  fs_system.h paging.h rtc.h idt.h intr_link.h
systemcalls.o: systemcalls.c systemcalls.h types.h x86_desc.h lib.h \
  keyboard.h multiboot.h i8259.h debug.h tests.h terminal.h scheduling.h \
  fs_system.h paging.h rtc.h idt.h intr_link.h
terminal.o: terminal.c terminal.h keyboard.h multiboot.h types.h \
  x86_desc.h lib.h i8259.h debug.h tests.h systemcalls.h fs_system.h \
  paging.h rtc.h idt.h intr_link.h scheduling.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h keyboard.h multiboot.h \
  i8259.h debug.h systemcalls.h terminal.h scheduling.h fs_system.h \
  paging.h rtc.h idt.h intr_link.h
